version: "3.7"
services:
   db:
       image: postgres
       restart: always
       user: postgres
       container_name: meal-service-db
       environment:
           POSTGRES_PASSWORD: postgres
           POSTGRES_USER: postgres
           POSTGRES_DB: meal_service
       ports:
           - '8000:8001'
