version: "3.7"
services:
   db:
       image: postgres
       environment:
           POSTGRES_PASSWORD: postgres
           POSTGRES_USER: postgres
           POSTGRES_DB: meal_service
       volumes:
           - ./pgdata
       ports:
           - '8000:8001'
